name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read


defaults:
  run:
    shell: bash
env:
  TF_VERSION: 'latest'
  #tok- vadPnf7rJ6hIxA.atlasv1.SX1o2c1ARivMfHx6vSnyGfN6gEiBmTZsDsVeoia90UvY4OSwEyUKQvSSmEE8eiO34vk
  #SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  #SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
  #SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
  #SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
  #ROOT_PATH: '${{github.workspace}}/'
jobs:
  snowflake-terraform-demo:
    name: "Snowflake Terraform Demo Job"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspaces: [./workspace1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init
        #working-directory: ${{ env.ROOT_PATH }}

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        #working-directory: ${{ env.ROOT_PATH }}

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        #working-directory: ${{ env.ROOT_PATH }}
    
